# Generated by Django 5.0.6 on 2026-06-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='object_key',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
