"""
Product model.

Design decisions:
- Vendor owns the product (ForeignKey to Vendor).
- Category is required (ForeignKey to Category).
- stock_quantity is NOT here — inventory table is the single source of truth.
- slug for clean URLs and SEO.
- status controls visibility: DRAFT -> ACTIVE -> INACTIVE.
- Soft delete via BaseModel — deleting a product never breaks order history.
- product_images is a reverse relation added by the ProductImage model.
"""
from django.db import models
from django.utils.text import slugify
from common.models import BaseModel
from common.validators import validate_positive_price, validate_sku


class ProductStatus(models.TextChoices):
    DRAFT = "DRAFT", "Draft"
    ACTIVE = "ACTIVE", "Active"
    INACTIVE = "INACTIVE", "Inactive"
    SUSPENDED = "SUSPENDED", "Suspended"


class Product(BaseModel):
    """
    A product listed by a vendor.
    Stock quantity lives in the Inventory model, not here.
    """
    vendor = models.ForeignKey(
        "vendors.Vendor",
        on_delete=models.CASCADE,
        related_name="products",
    )
    category = models.ForeignKey(
        "categories.Category",
        on_delete=models.PROTECT,
        related_name="products",
    )
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    brand = models.CharField(max_length=100, blank=True)
    sku = models.CharField(
        max_length=100,
        unique=True,
        validators=[validate_sku],
    )
    price = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        validators=[validate_positive_price],
    )
    slug = models.SlugField(max_length=300, unique=True, blank=True)
    status = models.CharField(
        max_length=20,
        choices=ProductStatus.choices,
        default=ProductStatus.DRAFT,
        db_index=True,
    )

    class Meta:
        db_table = "products"
        verbose_name = "Product"
        verbose_name_plural = "Products"
        ordering = ["-created_at"]
        indexes = [
            models.Index(fields=["vendor", "status"]),
            models.Index(fields=["category", "status"]),
            models.Index(fields=["sku"]),
            models.Index(fields=["slug"]),
        ]

    def __str__(self):
        return f"{self.name} ({self.sku})"

    def save(self, *args, **kwargs):
        if not self.slug:
            base_slug = slugify(f"{self.name}-{self.sku}")
            self.slug = base_slug
        super().save(*args, **kwargs)

    @property
    def primary_image(self):
        return self.product_images.filter(is_primary=True).first()


class ProductImage(BaseModel):
    """
    Product image stored on AWS S3.
    URL is stored here after the client uploads directly to S3
    via a presigned URL generated by the images app.
    """
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name="product_images",
    )
    image_url = models.URLField(max_length=1000)
    is_primary = models.BooleanField(default=False, db_index=True)
    display_order = models.PositiveIntegerField(default=0)

    class Meta:
        db_table = "product_images"
        verbose_name = "Product Image"
        verbose_name_plural = "Product Images"
        ordering = ["display_order", "-is_primary"]
        indexes = [
            models.Index(fields=["product", "is_primary"]),
        ]

    def __str__(self):
        return f"Image for {self.product.name} (primary={self.is_primary})"

    def save(self, *args, **kwargs):
        """
        Ensure only one primary image per product.
        If this image is set as primary, demote all others.
        """
        if self.is_primary:
            ProductImage.objects.filter(
                product=self.product,
                is_primary=True,
            ).exclude(pk=self.pk).update(is_primary=False)
        super().save(*args, **kwargs)