# Generated by Django 5.0.6 on 2026-06-13 16:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(blank=True, db_index=True, max_length=36),
                ),
                ("actor_email", models.EmailField(blank=True, max_length=254)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("VENDOR_CREATED", "Vendor Created"),
                            ("VENDOR_UPDATED", "Vendor Updated"),
                            ("VENDOR_APPROVED", "Vendor Approved"),
                            ("VENDOR_SUSPENDED", "Vendor Suspended"),
                            ("CATEGORY_CREATED", "Category Created"),
                            ("CATEGORY_UPDATED", "Category Updated"),
                            ("CATEGORY_DELETED", "Category Deleted"),
                            ("PRODUCT_CREATED", "Product Created"),
                            ("PRODUCT_UPDATED", "Product Updated"),
                            ("PRODUCT_DELETED", "Product Deleted"),
                            ("INVENTORY_UPDATED", "Inventory Updated"),
                            ("IMAGE_UPLOADED", "Image Uploaded"),
                            ("IMAGE_DELETED", "Image Deleted"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                (
                    "entity_id",
                    models.CharField(blank=True, db_index=True, max_length=36),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor_id", "action"],
                        name="audit_logs_actor_i_cf1ffa_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="audit_logs_entity__d4c2e5_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_logs_action_391715_idx",
                    ),
                ],
            },
        ),
    ]
